### ISSUE TITLE
Inline BelongsToMany field

### ISSUE THREAD

**Issue by timcv** [dcasia/conditional-container#10]
Do you have any idea about how to get it working with NovaAttachMany och BelongsToManyField?

The attributeValue for NovaAttachMany is a JSON (or string, not shure) like [1,12,3]. And my problem is that for example "roles contains 1" will match both 1 and 12.

The attributeValue BelongsToManyField is an object and i cant compare to objects..

Do you have any idea how to make a field dependent on an Inline ManyToMany field with your field?

/Tim

**Comment by timcv** [comment]
https://github.com/dillingham/nova-attach-many
https://github.com/Benjacho/belongs-to-many-field-nova

**Comment by milewski** [comment]
Uhm... That contains rule uses 'str.includes()' function if the field stores an array it wouldn't work... Perhaps that function can be updated to indexOf so it would work on str and on array

**Comment by milewski** [comment]
Hi @timcv , I had a closer look into the `nova-attach-many` to see what is preventing this field to work with that package and that field stores and retrieves everything through ajax, which would make it impossible for `conditional-container` to determine what are the selected values... 

However, there were a few small improvements I could make to make it work (almost seamlessly)

```php
public function fields(Request $request)
{

    $this->resource->loadMissing('roles'); // Important!!

    return [

        AttachMany::make('Roles'),

        ConditionalContainer::make([
            Text::make('Test', 'test')->rules('required'),
        ])->if('roles contains 1'),

    ];
}
```

So on the example above you need to load manually `$this->resource->loadMissing('roles');` because `AttachMany` doesn't do it for you!

**Comment by milewski** [comment]
I have figured out a way to remove that manual `loadMissing()` call, now on version [v1.1.1](https://github.com/dcasia/conditional-container/releases/tag/v1.1.1) everything should work as expected.

-----

>The attributeValue for NovaAttachMany is a JSON (or string, not shure) like [1,12,3]. And my problem is that for example "roles contains 1" will match both 1 and 12.

and here I think it is expected that `roles contains 1` matches `1, 12, 000001, etc...` the correct, if you are matching an specific ID, should have been `roles === 1` etc.. and if you need match multiple roles you can write `roles === 1 OR roles === 2` etc...
