### ISSUE TITLE
MorphTo field with AND condition not working

### ISSUE THREAD

**Issue by abishekrsrikaanth** [dcasia/conditional-container#22]
I have a `morphTo` with an `AND` condition as shown below. I can't seem to get this to work. Can you please let me know if I am missing something?

```php
MorphTo::make('Invoice Type', 'buyable')->types([
                Classes::class,
                Product::class,
            ]),

            ConditionalContainer::make([
                RadioButton::make('Discountable')->options([
                    'YES' => 'Yes',
                    'NO'  => 'No',
                ]),
            ])->if('(buyable = '.Classes::uriKey().' AND buyable.type = "SUBSCRIPTION")'),
```

**Comment by milewski** [comment]
only `buyable = Classes::uriKey()` is valid, you cant depend on `buyable.type` it wont work

**Comment by abishekrsrikaanth** [comment]
@milewski, So, how do I go about adding this condition? 

```
if(get_class($buyable) == Classes::class && $buyable->type == 'SUBSCRIPTION')
```

**Comment by milewski** [comment]
This package doesn't support accessing a sub property of any model example: `->type`, so currently it's not possible to parse your AND condition due to this limitation

**Comment by abishekrsrikaanth** [comment]
@milewski, thanks for the info. The other package that you referred doesn't help me with what I am trying to do. Is accessing the property of a model be added as an enhancement. 

Is it not possible to access the chosen value of the `MorphTo` relation? `MorphTo` adds 2 fields (type, type_id).

**Comment by milewski** [comment]
Morph to adds 2 fields (buyable, buyable_id) yeah but this two properties exist on your main resource, in order to know the 'type' this package would also need to load your relationship so the 'type' property you are looking for would be available for comparation,

Another problem would be on edit view/create view, when choosing your MorphTo resource nova would need to send the loaded resource down though their Api which isn't what current they do they essentially just sends the 'id' down not every property so it would require a custom MorphTo field to be able to archive this
